devices/urls.py
from django.urls import path
from . import views

app_name = "devices"
urlpatterns = [
    path("list/", views.DeviceListView.as_view(), name="list"),
    path("new/", views.DeviceCreateView.as_view(), name="create"),
    path("<int:pk>/", views.DeviceDetailViev.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DeviceDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.DeviceUpdateView.as_view(), name="update"),
]

dj42_proj/urls.py
from django.contrib import admin
from django.urls import include, path

from landing.views import Home

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("accounts/", include("accounts.urls")),
    path("customers/", include("customers.urls")),
    path("devices/", include("devices.urls")),
    path("devices_assignments/", include("devices_assignments.urls")),
    path("admin/", admin.site.urls),
    path("mac_address_types/", include("mac_address_types.urls")),
]

devices/models.py
import uuid

from django.core.validators import MinLengthValidator
from django.db import models
from django.db.models import UniqueConstraint
from django.urls import reverse

from common.models import ValidityInfo
from customers.models import Customer


class DeviceManager(models.Manager):
    def get_by_natural_key(self, code):
        return self.get(code=code)


class Device(ValidityInfo):
    code = models.CharField(unique=True, max_length=6, null=False, blank=False)
    customers = models.ManyToManyField(
        Customer, through="DeviCustAssignment", related_name="devices"
    )
    name = models.CharField(max_length=120, null=True, blank=True)

    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    ipv4 = models.GenericIPAddressField(
        protocol="IPv4", blank=True, null=True, default=None
    )
    ipv6 = models.GenericIPAddressField(
        protocol="IPv6", blank=True, null=True, default=None
    )

    objects = DeviceManager()

    class Meta:
        managed = True
        verbose_name = "device"
        verbose_name_plural = "devices"

        db_table = "devices"  # 'core"."devices'
        db_table_comment = (
            "Devices to be managed such as Webcam, Sensors, System-On-Module (SOM)"
        )
        indexes = [
            models.Index(fields=["name"], name="devices_ix01"),
        ]

    def __str__(self):
        return f"[{self.code}] {self.name}"

    def get_absolute_url(self):
        return reverse("devices:list")

    def get_macaddress(self):
        return self.macaddress_set.all()

    def natural_key(self):
        return self.code


class DeviCustAssignment(ValidityInfo):
    CLOSING_REASON_TYPE = [
        ("SCH", "Scheduled"),
        ("EOC", "End of Contract"),
        ("DEC", "Decommissioned"),
        ("OOO", "Out Of Order"),
    ]
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    # Campos adicionales
    closing_reason_type = models.CharField(
        max_length=3,
        validators=[MinLengthValidator(3)],
        choices=CLOSING_REASON_TYPE,
        null=True,
        blank=True,
    )
    closing_remarks = models.TextField(max_length=600, null=True, blank=True)

    class Meta:
        managed = True
        verbose_name = "Device Customer Assignment"
        verbose_name_plural = "Device Customer Assignments"

        db_table = "devi_cust_assignments"  # 'core"."devi_cust_assignments'
        db_table_comment = "Assignments of devices to customers"

        # Seún lo recomendado:
        # https://docs.djangoproject.com/en/4.2/ref/models/options/#unique-together
        # Si se implementa con UniqueConstraints
        # IMPORTANTE: Se debe utilizar los campos del modelo y no los de la BD,
        # si se utiliza los campos de la BD: 'customer_id', 'device_id' todo funciona
        # al hacer makemigrations y migrate, sin embargo, no funcionan bien las
        # validaciones del form.is_valid()

        constraints = [
            UniqueConstraint(
                fields=["customer", "device", "active_from"],
                name="devi_cust_assignment_uk01",
            ),
        ]

    def get_absolute_url(self):
        return reverse("devices:list")

    def __str__(self):
        return f"{self.device}"

devices/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from devices.models import Device
from mac_addresses.forms import MacAddressForm
from mac_addresses.models import MacAddress

DeviceMacAddressFormset = inlineformset_factory(
    Device,
    MacAddress,
    form=MacAddressForm,
    extra=0,
    can_delete=True,
    can_delete_extra=True,
)


class DeviceForm(forms.ModelForm):
    active = forms.BooleanField(initial=True, required=False)

    def __init__(self, *args, **kwargs):
        super(DeviceForm, self).__init__(*args, **kwargs)
        self.fields["active"].disabled = True
        self.fields["created_by"].disabled = True
        self.fields["updated_by"].disabled = True

        instance = getattr(self, "instance", None)
        if instance and instance.pk:
            self.fields["active"].initial = instance.active

    class Meta:
        model = Device

        fields = [
            "id",
            "code",
            "name",
            "ipv4",
            "ipv6",
            "active",
            "active_from",
            "active_until",
            "created_by",
            "updated_by",
        ]

        widgets = {
            "code": forms.TextInput(
                attrs={
                    "placeholder": "code",
                }
            ),
            "name": forms.TextInput(
                attrs={
                    "placeholder": "name",
                }
            ),
            "ipv4": forms.TextInput(
                attrs={
                    "placeholder": "nnn.nnn.nnn.nnn",
                }
            ),
            "ipv6": forms.TextInput(
                attrs={
                    "placeholder": "IP V6 format",
                }
            ),
            "active_from": forms.DateTimeInput(
                format="%Y-%m-%d %H:%M:%S",
                attrs={
                    "class": "datetimefield",
                    "placeholder": "YYYY-MM-DD HH24:MI:SS",
                },
            ),
            "active_until": forms.DateTimeInput(
                format="%Y-%m-%d %H:%M:%S",
                attrs={
                    "class": "datetimefield",
                    "placeholder": "YYYY-MM-DD HH24:MI:SS",
                },
            ),
        }

devices/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.db.models import Q
from .models import Device
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
)

from django.views.generic.edit import CreateView, UpdateView

from .forms import DeviceForm, DeviceMacAddressFormset


class DeviceListView(LoginRequiredMixin, ListView):
    model = Device
    fields = "__All__"
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        query = self.request.GET.get("q")
        if query:
            loockups = Q(code__icontains=query) | Q(name__icontains=query)
            qs = Device.objects.filter(loockups)
        else:
            qs = super(DeviceListView, self).get_queryset(*args, **kwargs)

        return qs.order_by("-id")

    def get_template_names(self):
        if self.request.htmx and not self.request.htmx.history_restore_request:
            return "devices/partials/device_table.html"
        return "devices/device_list.html"


class DeviceInline:
    form_class = DeviceForm
    model = Device
    template_name = "devices/device_create_or_update.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()

        # if not all((x.is_valid() for x in named_formsets.values())):
        #     return self.render_to_response(self.get_context_data(form=form))

        all_valid = True
        for x in named_formsets.values():
            if not x.is_valid():
                all_valid = False
        if not all_valid:
            return self.render_to_response(self.get_context_data(form=form))

        obj = form.save(commit=False)
        if obj.id:
            obj.updated_by = self.request.user
        else:
            obj.created_by = self.request.user
            obj.updated_by = self.request.user

        self.object = form.save()

        # for every formset, attempt to find a specific formset save function
        # otherwise, just save.
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, "formset_{0}_valid".format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect("devices:list")

    def formset_macaddress_set_valid(self, formset):
        """
        Hook for custom formset saving.. useful if you have multiple formsets
        """

        macaddresses = formset.save(commit=False)
        # add this, if you have can_delete=True parameter set in
        # inlineformset_factory func

        for obj in formset.deleted_objects:
            obj.delete()

        for macaddress in macaddresses:
            if macaddress.id:
                macaddress.updated_by = self.request.user
            else:
                macaddress.created_by = self.request.user
                macaddress.updated_by = self.request.user

            macaddress.device = self.object
            macaddress.save()


class DeviceCreateView(
    SuccessMessageMixin, LoginRequiredMixin, DeviceInline, CreateView
):
    success_message = 'Device "%(name)s" was created successfully'

    def get_context_data(self, **kwargs):
        context = super(DeviceCreateView, self).get_context_data(**kwargs)
        context["named_formsets"] = self.get_named_formsets()

        return context

    def get_initial(self):
        initial = super(DeviceCreateView, self).get_initial()
        initial["created_by"] = self.request.user
        initial["updated_by"] = self.request.user
        return initial

    def get_named_formsets(self):
        if self.request.method == "POST":
            return {
                "macaddress_set": DeviceMacAddressFormset(
                    self.request.POST or None,
                    self.request.FILES or None,
                    prefix="macaddress_set",
                ),
                # "images": ImageFormSet(
                #     self.request.POST or None,
                #     self.request.FILES or None,
                #     prefix="images",
                # ),
            }

        else:
            return {
                "macaddress_set": DeviceMacAddressFormset(prefix="macaddress_set"),
                # 'images': ImageFormSet(prefix='images'),
            }


class DeviceUpdateView(
    SuccessMessageMixin, LoginRequiredMixin, DeviceInline, UpdateView
):
    success_message = 'Device "%(name)s" was updated successfully'

    def get_context_data(self, **kwargs):
        context = super(DeviceUpdateView, self).get_context_data(**kwargs)
        context["named_formsets"] = self.get_named_formsets()
        return context

    def get_named_formsets(self):
        return {
            "macaddress_set": DeviceMacAddressFormset(
                self.request.POST or None,
                self.request.FILES or None,
                instance=self.object,
                prefix="macaddress_set",
            ),
            # "images": ImageFormSet(
            #     self.request.POST or None,
            #     self.request.FILES or None,
            #     instance=self.object,
            #     prefix="images",
            # ),
        }


class DeviceDetailViev(LoginRequiredMixin, DetailView):
    model = Device


class DeviceDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Device
    success_url = reverse_lazy("devices:list")
    success_message = 'Device "%(name)s" was deleted successfully'

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = reverse_lazy("devices:list")
            return HttpResponseRedirect(url)
        else:
            return super(DeviceDeleteView, self).post(request, *args, **kwargs)

    def form_valid(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super(DeviceDeleteView, self).delete(request, *args, **kwargs)

devices/templates/devices/partials/device_table.html
<!-- Table for device information -->
<div id="global-list-table">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Code</th>
                <th scope="col">Name</th>
                <th scope="col">Active</th>
                <th scope="col">UUID</th>
                <th scope="col">IPv4</th>
                <th scope="col">Created By</th>
                <th scope="col">Creation Date</th>
                <th scope="col">Updated By</th>
                <th scope="col">Update Date</th>
                <th scope="col"></th>
                <th scope="col">
                    <a href="{% url 'devices:create' %}">
                        <div class="gap-2 col-8 mx-auto justify-content-md-end">
                            <button type="button" class="btn btn-secondary btn-block btn-sm">Add</button>
                        </div>
                    </a>
                </th>
            </tr>
        </thead>
        <tbody>
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}" id="success-alert" style="opacity: 500;"{% else %} class="text-center alert alert-info alert-dismissible shadow fade show" {% endif %}>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important:{% endif %}
                        <strong>{{ message }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            {% for device in object_list %}
                <tr>
                    <td id="{{ device.id }}">
                        <a href="#{{ device.id }}" title="Permalink to this item">{{ device.id }}</a>
                    </td>
                    <td>{{ device.code }}</td>
                    <td>
                        <a href="{% url 'devices:detail' device.pk %}"  title="Detail">{{ device.name }}</a>
                    </td>
                    <td>
                        <input id="id_active" type="checkbox" {{ device.active|yesno:"checked," }} disabled>
                    </td>
                    <td>{{ device.uuid|default_if_none:"--" }}</td>
                    <td>{{ device.ipv4|default_if_none:"--" }}</td>
                    <td>{{ device.created_by|default_if_none:"--" }}</td>
                    <td>{{ device.created_at|date:'Y-m-d H:i:s' }}</td>
                    <td>{{ device.updated_by }}</td>
                    <td>{{ device.updated_at|date:'Y-m-d H:i:s' }}</td>
                    <td>
                        <a href="{% url 'devices:update' device.pk %}">
                            <button type="button" class="btn btn-primary btn-sm">Edit</button>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'devices:delete' device.pk %}">
                            <button type="button" class="btn btn-danger btn-sm">Delete</button>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <li>No devices yet.</li>
            {% endfor %}
        </tbody>
    </table>
    {% include "paginator.html" %}
</div>