devices/urls.py
from django.urls import path
from . import views

app_name = "devices"
urlpatterns = [
    path("list/", views.DeviceListView.as_view(), name="list"),
    path("new/", views.DeviceCreateView.as_view(), name="create"),
    path("<int:pk>/", views.DeviceDetailViev.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DeviceDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.DeviceUpdateView.as_view(), name="update"),
]

dj42_proj/urls.py
from django.contrib import admin
from django.urls import include, path

from landing.views import Home

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("accounts/", include("accounts.urls")),
    path("customers/", include("customers.urls")),
    path("devices/", include("devices.urls")),
    path("devices_assignments/", include("devices_assignments.urls")),
    path("admin/", admin.site.urls),
    path("mac_address_types/", include("mac_address_types.urls")),
]

mac_address_types/urls.py
from django.urls import path
from . import views

app_name = "mac_address_types"
urlpatterns = [
    path("list/", views.MacAddressTypeListView.as_view(), name="list"),
    path("new/", views.MacAddressTypeCreateView.as_view(), name="create"),
    path("<int:pk>/", views.MacAddressTypeDetailViev.as_view(), name="detail"),
    path("<int:pk>/delete/", views.MacAddressTypeDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.MacAddressTypeUpdateView.as_view(), name="update"),
]

mac_address_types/models.py
from django.db import models
from common.models import ValidityInfo

# from django.conf import settings
from django.urls import reverse


class MacAddressType(ValidityInfo):
    code = models.CharField(unique=True, max_length=12, null=True, blank=False)
    name = models.CharField(max_length=120, null=True, blank=True)
    desc = models.TextField(max_length=600, null=True, blank=True)

    class Meta:
        managed = True
        verbose_name = "MAC Address Type"
        verbose_name_plural = "MAC Address Types"
        db_table = "mac_address_types"  # 'core"."mac_address_types'
        db_table_comment = (
            "Media Access Control (MAC) Address Type."
            + "Types: Unicast MAC address; Multicast MAC address; Broadcast MAC address"
        )

    def __str__(self):
        return f"[{self.code}] {self.desc}"

    def get_absolute_url(self):
        return reverse("mac_address_types:list")

mac_address_types/forms.py
from django import forms
from django.conf import settings

from mac_address_types.models import MacAddressType


class MacAddressTypeForm(forms.ModelForm):
    active = forms.BooleanField(initial=True, required=False)

    def __init__(self, *args, **kwargs):
        super(MacAddressTypeForm, self).__init__(*args, **kwargs)
        self.fields["active"].disabled = True
        self.fields["created_by"].disabled = True
        self.fields["updated_by"].disabled = True

        instance = getattr(self, "instance", None)
        if instance and instance.pk:
            self.fields["active"].initial = instance.active

    class Meta:
        model = MacAddressType

        fields = [
            "id",
            "code",
            "name",
            "desc",
            "active",
            "active_from",
            "active_until",
            "created_by",
            "updated_by",
        ]
        widgets = {
            "code": forms.TextInput(
                attrs={
                    "placeholder": "code",
                }
            ),
            "name": forms.TextInput(
                attrs={
                    "placeholder": "name",
                }
            ),
            "desc": forms.Textarea(
                attrs={"placeholder": "Description", "rows": settings.TA_DEFAULT_ROWS},
            ),
            # "active": forms.CheckboxInput(),
            "active_from": forms.DateTimeInput(
                format="%Y-%m-%d %H:%M:%S",
                attrs={
                    "class": "datetimefield",
                    "placeholder": "YYYY-MM-DD HH24:MI:SS",
                },
            ),
            "active_until": forms.DateTimeInput(
                format="%Y-%m-%d %H:%M:%S",
                attrs={
                    "class": "datetimefield",
                    "placeholder": "YYYY-MM-DD HH24:MI:SS",
                },
            ),
        }

mac_address_types/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.db.models import Q
from .models import MacAddressType
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
)

from .forms import MacAddressTypeForm


class MacAddressTypeListView(LoginRequiredMixin, ListView):
    model = MacAddressType
    fields = "__All__"
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        query = self.request.GET.get("q")
        if query:
            loockups = (
                Q(code__icontains=query)
                | Q(name__icontains=query)
                | Q(desc__icontains=query)
            )
            qs = MacAddressType.objects.filter(loockups)
        else:
            qs = super(MacAddressTypeListView, self).get_queryset(*args, **kwargs)

        return qs.order_by("-id")

    def get_template_names(self):
        if self.request.htmx and not self.request.htmx.history_restore_request:
            return "mac_address_types/partials/macaddresstype_table.html"
        return "mac_address_types/macaddresstype_list.html"


class MacAddressTypeCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = MacAddressType
    form_class = MacAddressTypeForm
    success_message = 'MacAddressType "%(name)s" was created successfully'

    def get_initial(self):
        initial = super(MacAddressTypeCreateView, self).get_initial()
        initial["created_by"] = self.request.user
        initial["updated_by"] = self.request.user
        return initial

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.updated_by = self.request.user
        obj.save()
        return super(MacAddressTypeCreateView, self).form_valid(form)


class MacAddressTypeUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = MacAddressType
    success_message = 'MacAddressType "%(name)s" was updated successfully'

    form_class = MacAddressTypeForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.updated_by = self.request.user
        obj.save()
        return super(MacAddressTypeUpdateView, self).form_valid(form)


class MacAddressTypeDetailViev(LoginRequiredMixin, DetailView):
    model = MacAddressType
    fields = "__all__"


class MacAddressTypeDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = MacAddressType
    success_url = reverse_lazy("mac_address_types:list")
    success_message = 'MacAddressType "%(name)s" was deleted successfully'

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = reverse_lazy("mac_address_types:list")
            return HttpResponseRedirect(url)
        else:
            return super(MacAddressTypeDeleteView, self).post(request, *args, **kwargs)

    def form_valid(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super(MacAddressTypeDeleteView, self).delete(request, *args, **kwargs)

mac_address_types/templates/mac_address_types/partials/macaddresstype_table.html
<!-- Table for mac_address_type information -->
<div id="global-list-table">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Code</th>
                <th scope="col">Name</th>
                <th scope="col">Desc</th>
                <th scope="col">Active</th>
                <th scope="col">Created By</th>
                <th scope="col">Creation Date</th>
                <th scope="col">Updated By</th>
                <th scope="col">Update Date</th>
                <th scope="col"></th>
                <th scope="col">
                    <a href="{% url 'mac_address_types:create' %}">
                        <div class="gap-2 col-8 mx-auto justify-content-md-end">
                            <button type="button" class="btn btn-secondary btn-block btn-sm">Add</button>
                        </div>
                    </a>
                </th>
            </tr>
        </thead>
        <tbody>
            {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}" id="success-alert" style="opacity: 500;"
                    {% else %} class="text-center alert alert-info alert-dismissible shadow fade show" {% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important:{% endif %}
                    <strong>{{ message }}</strong>
                </div>
                {% endfor %}
            {% endif %}
            {% for mac_address_type in object_list %}
                <tr>
                    <td id="{{ mac_address_type.id }}">
                        <a href="#{{ mac_address_type.id }}" title="Permalink to this item">{{ mac_address_type.id }}</a>
                    </td>
                    <td>{{ mac_address_type.code }}</td>
                    <td>
                        <a href="{% url 'mac_address_types:detail' mac_address_type.pk %}" title="Detail">
                            {{mac_address_type.name|default_if_none:"N/A" }}
                        </a>
                    </td>
                    <td>{{ mac_address_type.desc|default_if_none:"N/A" }}</td>
                    <td>
                        <input id="id_active" type="checkbox" {{ mac_address_type.active|yesno:"checked," }} disabled>
                    </td>
                    <td>{{ mac_address_type.created_by|default_if_none:"--" }}</td>
                    <td>{{ mac_address_type.created_at|date:'Y-m-d H:i:s' }}</td>
                    <td>{{ mac_address_type.updated_by }}</td>
                    <td>{{ mac_address_type.updated_at|date:'Y-m-d H:i:s' }}</td>
                    <td>
                        <a href="{% url 'mac_address_types:update' mac_address_type.pk %}">
                            <button type="button" class="btn btn-primary btn-sm">Edit</button>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'mac_address_types:delete' mac_address_type.pk %}">
                            <button type="button" class="btn btn-danger btn-sm">Delete</button>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <li>No mac_address_types yet.</li>
            {% endfor %}
        </tbody>
    </table>
    {% include "paginator.html" %}
</div>