customers/urls.py
from django.urls import path
from . import views

app_name = "customers"
urlpatterns = [
    path("list/", views.CustomerListView.as_view(), name="list"),
    path("new/", views.CustomerCreateView.as_view(), name="create"),
    path("<int:pk>/", views.CustomerDetailViev.as_view(), name="detail"),
    path("<int:pk>/delete/", views.CustomerDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.CustomerUpdateView.as_view(), name="update"),
]

devices/urls.py
from django.urls import path
from . import views

app_name = "devices"
urlpatterns = [
    path("list/", views.DeviceListView.as_view(), name="list"),
    path("new/", views.DeviceCreateView.as_view(), name="create"),
    path("<int:pk>/", views.DeviceDetailViev.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DeviceDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.DeviceUpdateView.as_view(), name="update"),
]

devices_assignments/urls.py
from django.urls import path
from devices_assignments import views

app_name = "devices_assignments"
urlpatterns = [
    # path("<int:customer_pk>/", views.CustomerCreateView.as_view(), name="create"),
    # path("list/", views.DeviceListView.as_view(), name="list"),
    # path("<int:pk>/", views.DeviceDetailViev.as_view(), name="detail"),
    # path("<int:pk>/delete/", views.DeviceDeleteView.as_view(), name="delete"),
    path("<int:pk>/", views.CustomerUpdateView.as_view(), name="update"),
]

dj42_proj/urls.py
from django.contrib import admin
from django.urls import include, path

from landing.views import Home

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("accounts/", include("accounts.urls")),
    path("customers/", include("customers.urls")),
    path("devices/", include("devices.urls")),
    path("devices_assignments/", include("devices_assignments.urls")),
    path("admin/", admin.site.urls),
    path("mac_address_types/", include("mac_address_types.urls")),
]

customers/models.py
from django.db import models
from django.urls import reverse

from common.models import ValidityInfo


class Customer(ValidityInfo):
    code = models.CharField(unique=True, max_length=6, null=True, blank=False)
    name = models.CharField(max_length=120, null=True, blank=True)

    class Meta:
        managed = True
        verbose_name = "customer"
        verbose_name_plural = "customers"

        db_table = "customers"  # 'example"."customers'
        # db_table_comment = "Customers"
        # indexes = [
        #     models.Index(fields=["name"], name="customers_ix01"),
        # ]

    def __str__(self):
        return self.code

    def get_absolute_url(self):
        return reverse("customers:list")

customers/forms.py
from django import forms

from customers.models import Customer


class CustomerForm(forms.ModelForm):
    active = forms.BooleanField(initial=True, required=False)

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        self.fields["active"].disabled = True
        self.fields["created_by"].disabled = True
        self.fields["updated_by"].disabled = True

        instance = getattr(self, "instance", None)
        if instance and instance.pk:
            self.fields["active"].initial = instance.active

    class Meta:
        model = Customer

        fields = [
            "id",
            "code",
            "name",
            "active",
            "active_from",
            "active_until",
            "created_by",
            "updated_by",
        ]

        widgets = {
            "code": forms.TextInput(
                attrs={
                    "placeholder": "customer code",
                }
            ),
            "name": forms.TextInput(
                attrs={
                    "placeholder": "name",
                }
            ),
            "active_from": forms.DateTimeInput(
                format="%Y-%m-%d %H:%M:%S",
                attrs={
                    "class": "datetimefield",
                    "placeholder": "YYYY-MM-DD HH24:MI:SS",
                },
            ),
            "active_until": forms.DateTimeInput(
                format="%Y-%m-%d %H:%M:%S",
                attrs={
                    "class": "datetimefield",
                    "placeholder": "YYYY-MM-DD HH24:MI:SS",
                },
            ),
        }

customers/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.db.models import Q

from .models import Customer
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
)

from .forms import CustomerForm


class CustomerListView(LoginRequiredMixin, ListView):
    model = Customer
    fields = "__All__"
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        query = self.request.GET.get("q")
        if query:
            loockups = Q(code__icontains=query) | Q(name__icontains=query)
            qs = Customer.objects.filter(loockups)
        else:
            qs = super(CustomerListView, self).get_queryset(*args, **kwargs)

        return qs.order_by("-id")

    def get_template_names(self):
        if self.request.htmx and not self.request.htmx.history_restore_request:
            return "customers/partials/customer_table.html"
        return "customers/customer_list.html"

    # def get_paginate_by(self, queryset):
    #     result = self.request.GET.get("paginate_by", self.paginate_by)
    #     return self.request.GET.get("paginate_by", self.paginate_by)


class CustomerCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Customer
    form_class = CustomerForm
    success_message = 'Customer "%(name)s" was created successfully'

    def get_initial(self):
        initial = super(CustomerCreateView, self).get_initial()
        initial["created_by"] = self.request.user
        initial["updated_by"] = self.request.user
        return initial

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.updated_by = self.request.user
        obj.save()
        return super(CustomerCreateView, self).form_valid(form)


class CustomerUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Customer
    success_message = 'Customer "%(name)s" was updated successfully'

    form_class = CustomerForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        # obj.created_by = self.request.user
        obj.updated_by = self.request.user
        obj.save()
        return super(CustomerUpdateView, self).form_valid(form)


class CustomerDetailViev(LoginRequiredMixin, DetailView):
    model = Customer
    fields = "__all__"


class CustomerDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy("customers:list")
    success_message = 'Customer "%(name)s" was deleted successfully'

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = reverse_lazy("customers:list")
            return HttpResponseRedirect(url)
        else:
            return super(CustomerDeleteView, self).post(request, *args, **kwargs)

    def form_valid(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super(CustomerDeleteView, self).delete(request, *args, **kwargs)

customers/templates/customers/partials/customer_table.html
<!-- Table for customer information -->
<div id="global-list-table">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Code</th>
                <th scope="col">Name</th>
                <th scope="col">Active</th>
                <th scope="col">Created By</th>
                <th scope="col">Creation Date</th>
                <th scope="col">Updated By</th>
                <th scope="col">Update Date</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col">
                    <a href="{% url 'customers:create' %}">
                        <div class="gap-2 col-8 mx-auto justify-content-md-end">
                            <button type="button" class="btn btn-secondary btn-block btn-sm">Add</button>
                        </div>
                    </a>
                </th>
            </tr>
        </thead>
        <tbody>
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}" id="success-alert" style="opacity: 500;"{% else %} class="text-center alert alert-info alert-dismissible shadow fade show" {% endif %}>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important:{% endif %}
                        <strong>{{ message }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            {% for customer in object_list %}
                <tr>
                    <td id="{{ customer.id }}">
                        <a href="#{{ customer.id }}" title="Permalink to this item">{{ customer.id }}</a>
                    </td>
                    <td>{{ customer.code }}</td>
                    <td>
                        <a href="{% url 'customers:detail' customer.pk %}" title="Detail">{{ customer.name }}</a>
                    </td>
                    <td>
                        <input id="id_active" type="checkbox" {{ customer.active|yesno:"checked," }} disabled>
                    </td>
                    <td>{{ customer.created_by|default_if_none:"--" }}</td>
                    <td>{{ customer.created_at|date:'Y-m-d H:i:s' }}</td>
                    <td>{{ customer.updated_by }}</td>
                    <td>{{ customer.updated_at|date:'Y-m-d H:i:s' }}</td>
                    <td>
                        <a href="{% url 'customers:update' customer.pk %}">
                            <button type="button" class="btn btn-primary btn-sm">Edit</button>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'devices_assignments:update' customer.pk %}">
                            <button type="button" class="btn btn-secondary btn-sm">Devices</button>
                        </a>
                    </td>

                    <td>
                        <a href="{% url 'customers:delete' customer.pk %}">
                            <button type="button" class="btn btn-danger btn-sm">Delete</button>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <li>No customers yet.</li>
            {% endfor %}
        </tbody>
    </table>
    {% include "paginator.html" %}
</div>