accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path(
        "login/",
        views.login_view,
        name="login",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
]

customers/urls.py
from django.urls import path
from . import views

app_name = "customers"
urlpatterns = [
    path("list/", views.CustomerListView.as_view(), name="list"),
    path("new/", views.CustomerCreateView.as_view(), name="create"),
    path("<int:pk>/", views.CustomerDetailViev.as_view(), name="detail"),
    path("<int:pk>/delete/", views.CustomerDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.CustomerUpdateView.as_view(), name="update"),
]

devices/urls.py
from django.urls import path
from . import views

app_name = "devices"
urlpatterns = [
    path("list/", views.DeviceListView.as_view(), name="list"),
    path("new/", views.DeviceCreateView.as_view(), name="create"),
    path("<int:pk>/", views.DeviceDetailViev.as_view(), name="detail"),
    path("<int:pk>/delete/", views.DeviceDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.DeviceUpdateView.as_view(), name="update"),
]

dj42_proj/urls.py
from django.contrib import admin
from django.urls import include, path

from landing.views import Home

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("accounts/", include("accounts.urls")),
    path("customers/", include("customers.urls")),
    path("devices/", include("devices.urls")),
    path("devices_assignments/", include("devices_assignments.urls")),
    path("admin/", admin.site.urls),
    path("mac_address_types/", include("mac_address_types.urls")),
]

mac_address_types/urls.py
from django.urls import path
from . import views

app_name = "mac_address_types"
urlpatterns = [
    path("list/", views.MacAddressTypeListView.as_view(), name="list"),
    path("new/", views.MacAddressTypeCreateView.as_view(), name="create"),
    path("<int:pk>/", views.MacAddressTypeDetailViev.as_view(), name="detail"),
    path("<int:pk>/delete/", views.MacAddressTypeDeleteView.as_view(), name="delete"),
    path("<int:pk>/update/", views.MacAddressTypeUpdateView.as_view(), name="update"),
]

templates/base-bs5.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta name="description" content="Django 4.2 LTS Z2P - Español">
        <meta name="keywords" content="HTML, CSS3">
        <meta name="author" content="Marcelo Herrera Tejada">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
                Django 4.2 - dj42_proj - Español
            {% endblock title %}
        </title>
        <link rel="shortcut icon" type="image/png" href="{% static 'imgs/favicon.ico' %}" >

        <script src="https://unpkg.com/htmx.org@1.9.2"></script>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
              crossorigin="anonymous">

        {% block extrahead %}
        {% endblock extrahead %}
    </head>
    <body>
        {% include "navbar.html" %}
        <!-- Main Content -->
        <div class="container col-12 col-md-12 col-md-8 my-4">
            {% block content %}
            {% endblock content %}
        </div>
        <!-- End Main Content -->
        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
        </script>
        <!-- Ajax -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <!-- Local js -->


        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>


        <script src="{% static 'js/alerts.js' %}"></script>
        <script src="{% static 'js/datetimepicker.js' %}"></script>

    </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta name="description" content="Django 4.2 LTS Z2P - Español">
        <meta name="keywords" content="HTML, CSS3">
        <meta name="author" content="Marcelo Herrera Tejada">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
                Django 4.2 - dj42_proj - Español
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block extrahead %}
        {% endblock extrahead %}
    </head>
    <body>
        <!-- Navigation Bar -->
        <nav class="navbar">
            <div class="navbar__logo">
                <a href="{% url 'home' %}">Remote IoT Management</a>
            </div>
            <ul class="navbar__menu">
                <li>
                    <a href="{% url 'customers:list' %}">Customers</a>
                </li>
                <li>
                    <a href="#">Devices</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
            </ul>
        </nav>
        <!-- End Navigation Bar -->
        <!-- Main Content -->
        <div class="main-content">
            {% block content %}
            {% endblock content %}
        </div>
        <!-- End Main Content -->
    </body>
</html>

templates/messages.html
<td>
    {% for message in messages %}
        {% if message.tags %}
            <div class="alert alert-{{ message.tags }}" id="success-alert-{{ forloop.counter0 }}" role="alert">
                {{ message }}
            </div>
        {% else %}
            <div class="alert alert-info text-center alert-dismissible shadow fade show" id="success-alert-{{ forloop.counter0 }}" role="alert">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
</td>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Remote IoT Management</a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customers:list' %}">Customers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'devices:list' %}">Devices</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             href="#"
             role="button"
             data-bs-toggle="dropdown"
             aria-expanded="false">Otros</a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'mac_address_types:list' %}">MAC Address Types</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <span class="navbar-text">
          <b> {{ user.username }}</b>
        </span>
        <li>
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
      {% else %}
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      {% endif %}
    </div>
    <form class="d-flex"
          hx-get="{{ object.get_absolute_url }}"
          hx-target="#global-list-table"
          hx-swap="outerHTML"
          method='get'>
      <input class="form-control me-2"
             name="q"
             type="search"
             placeholder="Search"
             aria-label="Search"
             value="{{ request.GET.q }}"
             autocomplete="off">
             {% comment %}
             autocomplete="off" es para el caso de refresh/F5 en
             firefox ya que al hacer el refresh, no se limpia el campo "q" pero
             pero en la view  el self.request.GET.get("q") no encuentra el
             valor de q. Al pner autocomplete en off, hay consistencia entre
             lo mostrado en el Search y el filtro/paginacion
             TODO: Buscar la forma de actualizar el filtro independiente de
             si es un refresh en firefox. Obs.: Con CNTR+F5 si se limpia
             el valor del search (q)
             {% endcomment %}
      <button class="btn btn-outline-secondary" type="submit">Search</button>
    </form>
  </div>
</nav>

templates/paginator.html
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item enabled">
                <a class="page-link"
                   href="#"
                   hx-get="{{ object.get_absolute_url }}"
                   hx-vals='{"page": "{{ page_obj.first_page_number }}", "q": "{{ request.GET.q }}"}'
                   hx-target="#global-list-table"
                   hx-swap="outerHTML">&laquo; first</a>
            </li>
            <li class="page-item enabled">
                <a class="page-link"
                   href="#"
                   hx-get="{{ object.get_absolute_url }}"
                   hx-vals='{"page": "{{ page_obj.previous_page_number }}", "q": "{{ request.GET.q }}"}'
                   hx-target="#global-list-table"
                   hx-swap="outerHTML">previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">&laquo; first</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link">previous</a>
            </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link"
                       href="#"
                       aria-current="page"
                       hx-get="{{ object.get_absolute_url }}"
                       hx-vals='{"page": "{{ i }}", "q": "{{ request.GET.q }}"}'
                       hx-target="#global-list-table"
                       hx-swap="outerHTML">{{ i }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link"
                       href="#"
                       aria-current="page"
                       hx-get="{{ object.get_absolute_url }}"
                       hx-vals='{"page": "{{ i }}", "q": "{{ request.GET.q }}"}'
                       hx-target="#global-list-table"
                       hx-swap="outerHTML">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item enabled">
                <a class="page-link"
                   href="#"
                   hx-get="{{ object.get_absolute_url }}"
                   hx-vals='{"page": "{{ page_obj.next_page_number }}", "q": "{{ request.GET.q }}"}'
                   hx-target="#global-list-table"
                   hx-swap="outerHTML">next</a>
            </li>
            <li class="page-item enabled">
                <a class="page-link"
                   href="#"
                   hx-get="{{ object.get_absolute_url }}"
                   hx-vals='{"page": "{{ page_obj.paginator.num_pages }}", "q": "{{ request.GET.q }}"}'
                   hx-target="#global-list-table"
                   hx-swap="outerHTML">last &raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">next</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link">last &raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav>